# Generated by Django 2.1.2 on 2018-10-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hero_name', models.CharField(max_length=48, verbose_name='英雄名称')),
                ('hero_description', models.CharField(max_length=512, verbose_name='描述信息')),
                ('hero_photo', models.CharField(max_length=48, verbose_name='资源地址')),
            ],
        ),
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('heroTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('hero_type', models.CharField(max_length=32, verbose_name='英雄定位')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='heroType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honor.HeroType', verbose_name='英雄定位'),
        ),
    ]
