# Generated by Django 2.1.2 on 2018-10-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='heroType',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='HeroType',
        ),
    ]
