# Generated by Django 2.1.2 on 2018-10-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('honor', '0002_auto_20181016_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('hero_name', models.CharField(max_length=48, verbose_name='英雄名称')),
                ('hero_word', models.CharField(max_length=512, verbose_name='人物台词')),
                ('hero_photo', models.CharField(max_length=48, verbose_name='资源地址')),
            ],
            options={
                'verbose_name_plural': '王者荣耀英雄',
            },
        ),
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('heroTypeId', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('hero_type', models.CharField(max_length=32, verbose_name='英雄定位')),
            ],
            options={
                'verbose_name_plural': '王者荣耀英雄类别',
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='heroType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honor.HeroType', verbose_name='英雄定位'),
        ),
    ]
