# Generated by Django 2.1.2 on 2018-10-17 10:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0003_auto_20181016_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_gonglue',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_skill',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
