# Generated by Django 2.1.2 on 2018-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remajor', '0002_delete_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(1, '普通'), (2, '刷分')])),
                ('stu_id', models.IntegerField()),
                ('stu_name', models.CharField(max_length=32)),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=32)),
                ('profession', models.CharField(max_length=32)),
            ],
        ),
    ]
