# Generated by Django 2.1.2 on 2018-10-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remajor', '0005_rebuild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rebuild',
        ),
    ]
