# Generated by Django 2.1.2 on 2018-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remajor', '0006_delete_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=12, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('profession', models.CharField(max_length=32, verbose_name='专业')),
                ('choice', models.IntegerField(choices=[(1, '普通'), (2, '刷分')], verbose_name='重修方式')),
            ],
            options={
                'verbose_name_plural': '学生重修管理',
            },
        ),
    ]
