# Generated by Django 2.1.2 on 2018-10-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remajor', '0007_rebuild'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rebuild',
        ),
    ]
