# Generated by Django 2.0.2 on 2018-10-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0002_auto_20181023_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='use_goods',
        ),
    ]
