# Generated by Django 2.0.2 on 2018-10-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0003_remove_car_use_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixlist',
            name='car',
        ),
    ]
