# Generated by Django 2.0.2 on 2018-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0012_auto_20181023_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='password',
            field=models.CharField(default='12345678', max_length=20, verbose_name='密码'),
        ),
    ]
