# Generated by Django 2.0.2 on 2018-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0013_power_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='user_real_name',
            field=models.CharField(default='zz', max_length=30, verbose_name='真实姓名'),
        ),
    ]
