# Generated by Django 2.0.2 on 2018-10-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=32, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='car',
            name='use_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.Goods', verbose_name='使用配件'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='begin_fix_time',
            field=models.DateTimeField(auto_now=True, verbose_name='提交订单时间'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.Car', verbose_name='车'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.Worker', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.Car', verbose_name='车辆'),
        ),
    ]
