# Generated by Django 2.0.2 on 2018-10-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0004_remove_fixlist_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='price',
            field=models.IntegerField(default=0, verbose_name='交易价格'),
        ),
    ]
