# Generated by Django 2.0.2 on 2018-10-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0005_fixlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
