# Generated by Django 2.0.2 on 2018-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0011_auto_20181023_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name_plural': '人员权限记录'},
        ),
        migrations.RemoveField(
            model_name='power',
            name='only_record',
        ),
        migrations.AddField(
            model_name='power',
            name='boss',
            field=models.BooleanField(default=False),
        ),
    ]
