# Generated by Django 2.0.2 on 2018-10-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0014_power_user_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='main_goods',
            field=models.CharField(default='1', max_length=100, verbose_name='主要使用配件'),
        ),
        migrations.AlterField(
            model_name='fixlist',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfix.Worker', verbose_name='主要负责人'),
        ),
    ]
