# Generated by Django 2.0 on 2018-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfix', '0015_auto_20181023_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_made_order',
            field=models.BooleanField(default=False),
        ),
    ]
