# Generated by Django 2.0 on 2018-11-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0002_auto_20181104_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
