# Generated by Django 2.0 on 2018-11-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0004_auto_20181104_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '小说章节管理'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name_plural': '小说管理'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='novel_name',
        ),
        migrations.AddField(
            model_name='article',
            name='belong_novel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedfox.Novel', verbose_name='小说名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_name',
            field=models.CharField(max_length=60, verbose_name='小说名'),
        ),
    ]
