# Generated by Django 2.0 on 2018-11-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0005_auto_20181105_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
    ]
