# Generated by Django 2.0 on 2018-11-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0006_noveltype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noveltype',
            options={'verbose_name_plural': '小说分类'},
        ),
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='feedfox.NovelType'),
        ),
    ]
