# Generated by Django 2.0 on 2018-11-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0007_auto_20181105_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='feedfox.NovelType', verbose_name='小说类型'),
        ),
        migrations.AlterField(
            model_name='noveltype',
            name='type_name',
            field=models.CharField(max_length=32, verbose_name='小说分类'),
        ),
    ]
