# Generated by Django 2.0 on 2018-11-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0008_auto_20181107_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='描述'),
        ),
    ]
