# Generated by Django 2.0 on 2018-11-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0009_auto_20181108_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedfox.NovelType', verbose_name='小说类型'),
        ),
    ]
