# Generated by Django 2.0 on 2018-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedfox', '0015_remove_novel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
